name: '🐛 Bug'
description: '버그 발생했을 때 사용해 주세요.'
title: '🐛 [Bug] '
labels: ['bug']
type: 'bug'
body:
    - type: textarea
      attributes:
          label: 📄 버그 설명
          description: 버그에 대한 설명을 작성해 주세요.
          placeholder: 어떤 버그가 발생했는지 자세히 설명해주세요.
      validations:
          required: true
    - type: textarea
      attributes:
          label: 🔄 재현 단계
          description: 버그를 재현하기 위한 단계를 작성해 주세요.
          placeholder: |
              1. '...'로 이동
              2. '...' 클릭
              3. '...' 입력
              4. 에러 발생
      validations:
          required: true
    - type: textarea
      attributes:
          label: ✅ 예상 동작
          description: 정상적으로 동작했을 때 예상되는 결과를 작성해 주세요.
          placeholder: 어떤 결과가 나와야 하는지 설명해주세요.
      validations:
          required: true
    - type: textarea
      attributes:
          label: ❌ 실제 동작
          description: 실제로 발생한 동작을 작성해 주세요.
          placeholder: 실제로 어떤 문제가 발생했는지 설명해주세요.
      validations:
          required: true
    - type: dropdown
      attributes:
          label: 💻 운영체제
          description: 버그가 발생한 운영체제를 선택해 주세요.
          options:
              - Windows 10
              - Windows 11
              - macOS
              - Linux
      validations:
          required: true
    - type: input
      attributes:
          label: 📱 앱 버전
          description: 사용 중인 앱 버전을 입력해 주세요. ex) 1.0.0-alpha
          placeholder: 1.0.0-alpha
      validations:
          required: true
    - type: textarea
      attributes:
          label: 📸 스크린샷/로그
          description: 스크린샷이나 로그 파일이 있다면 첨부해 주세요.
          placeholder: 스크린샷을 드래그 앤 드롭하거나, 로그 내용을 붙여넣어주세요.
    - type: textarea
      attributes:
          label: 📋 추가 컨텍스트
          description: 버그와 관련된 추가 정보가 있다면 작성해 주세요.
          placeholder: 특정 조건에서만 발생하거나, 관련된 다른 이슈가 있다면 작성해주세요.
    - type: textarea
      attributes:
          label: 🧪 테스트 케이스 (선택사항)
          description: Playwright, Vitest 등으로 작성한 재현 가능한 테스트 코드가 있다면 작성해 주세요.
          placeholder: |
              ```typescript
              // Playwright 예시
              test('버그 재현', async ({ page }) => {
                await page.goto('/');
                // ...
              });

              // 또는 Vitest 예시
              describe('버그 재현', () => {
                it('should ...', () => {
                  // ...
                });
              });
              ```
    - type: textarea
      attributes:
          label: 📊 테스트 실행 결과 (선택사항)
          description: 테스트를 실행한 결과나 CI/CD에서 실패한 테스트 로그를 작성해 주세요.
          placeholder: 테스트 실행 결과, 실패한 테스트 로그, 또는 CI/CD 링크를 작성해주세요.
    - type: textarea
      attributes:
          label: ✅ 작업할 내용
          description: 할 일을 체크박스 형태로 작성해주세요.
          placeholder: |
              - [ ] 작업 1
              - [ ] 작업 2
              - [ ] 작업 3
      validations:
          required: true
    - type: textarea
      attributes:
          label: 🙋🏻 참고 자료
          description: 참고 자료가 있다면 작성해 주세요.
          placeholder: 관련 문서, 링크, 이슈 번호 등을 작성해주세요.
