name: '🐛 Bug'
description: '버그 발생했을 때 사용해 주세요.'
title: '🐛 [Bug] '
labels: ['bug']
type: 'bug'
body:
    - type: textarea
      attributes:
          label: 📄 버그 설명
          description: 버그에 대한 설명을 작성해 주세요.
          placeholder: 어떤 버그가 발생했는지 자세히 설명해주세요.
      validations:
          required: true
    - type: textarea
      attributes:
          label: 💻 실행 환경
          description: 버그가 발생한 환경을 설명해 주세요. ex) 앱 버전, 브라우저 버전 등
          default: |
          - 앱 버전: 
          - OS/디바이스: 
          - 브라우저/앱 채널: 
      validations:
          required: true
    - type: textarea
      attributes:
          label: 🧪 테스트 케이스 (선택사항)
          description: 버그를 재현하기 위한 테스트 코드 또는 단계가 있다면 작성해 주세요.
          placeholder: |
              ```typescript
              // Playwright 예시
              test('버그 재현', async ({ page }) => {
                await page.goto('/');
                // ...
              });

              // 또는 Vitest 예시
              describe('버그 재현', () => {
                it('should ...', () => {
                  // ...
                });
              });
              ```
      validations:
          required: true
    - type: textarea
      attributes:
          label: ✅ 예상 동작
          description: 정상적으로 동작했을 때 예상되는 결과를 한 줄 정도로 작성해 주세요.
          placeholder: 어떤 결과가 나와야 하는지 설명해주세요.
    - type: textarea
      attributes:
          label: ❌ 실제 동작
          description: 실제로 발생한 동작을 한 줄 정도로 작성해 주세요.
          placeholder: 실제로 어떤 문제가 발생했는지 설명해주세요.
    - type: textarea
      attributes:
          label: 📸 스크린샷/로그
          description: 스크린샷이나 로그 파일이 있다면 첨부해 주세요.
          placeholder: 스크린샷을 드래그 앤 드롭하거나, 로그 내용을 붙여넣어주세요.
    - type: textarea
      attributes:
          label: 📋 추가 컨텍스트
          description: 버그와 관련된 추가 정보가 있다면 작성해 주세요.
          placeholder: 특정 조건에서만 발생하거나, 관련된 다른 이슈가 있다면 작성해주세요.