name: '✨ Feature'
description: '새로운 기능 추가 요청 시 사용해 주세요.'
title: '✨ [Feature] '
labels: ['feature']
type: 'feature'
body:
    - type: textarea
      attributes:
          label: 📄 설명
          description: 새로운 기능에 대한 설명을 작성해 주세요.
          placeholder: 자세히 적을수록 좋습니다!
      validations:
          required: true
    - type: textarea
      attributes:
          label: 💡 사용 사례
          description: 이 기능이 어떤 상황에서 사용될지 설명해 주세요.
          placeholder: 어떤 문제를 해결하거나 어떤 사용자 경험을 개선하는지 설명해주세요.
    - type: textarea
      attributes:
          label: 🎯 기대 효과
          description: 이 기능이 추가되면 어떤 효과가 있을지 설명해 주세요.
          placeholder: 사용자 경험 개선, 작업 효율성 향상 등을 설명해주세요.
    - type: textarea
      attributes:
          label: 🧪 테스트 케이스 (선택사항)
          description: Playwright, Vitest 등으로 작성한 기능 테스트 코드가 있다면 작성해 주세요.
          placeholder: |
              ```typescript
              // Playwright 예시
              test('새로운 기능 테스트', async ({ page }) => {
                await page.goto('/');
                // ...
              });

              // 또는 Vitest 예시
              describe('새로운 기능', () => {
                it('should ...', () => {
                  // ...
                });
              });
              ```
    - type: textarea
      attributes:
          label: 📊 테스트 실행 결과 (선택사항)
          description: 테스트를 실행한 결과나 CI/CD에서 실행한 테스트 로그를 작성해 주세요.
          placeholder: 테스트 실행 결과, 테스트 로그, 또는 CI/CD 링크를 작성해주세요.
    - type: textarea
      attributes:
          label: ✅ 작업할 내용
          description: 할 일을 체크박스 형태로 작성해주세요.
          placeholder: |
              - [ ] 작업 1
              - [ ] 작업 2
              - [ ] 작업 3
      validations:
          required: true
    - type: textarea
      attributes:
          label: 🙋🏻 참고 자료
          description: 참고 자료가 있다면 작성해 주세요.
          placeholder: 관련 문서, 링크, 이슈 번호, 디자인 시안 등을 작성해주세요.
